### PR TITLE
providing a starting place to update github repo

### PR DESCRIPTION
**Pull request by amsos**
Provided some of the initial structures needed for the repo to be updated.

### CODE REVIEW

**Comment by amsos** [comment]
Not sure if it's worth creating a different branch to start?  @alexrandaccio

**Review by alexrandaccio — APPROVED** [review]

**Comment by alexrandaccio** [comment]
I don't think a separate branch is necessary since we're starting from nothing. I say merge away

**Comment by will-holley** [comment]
And the ball is rolling! Can you drop the implementations dir? Would prefer to implement a standard convention (e.g. `src/`) in a subsequent PR.

**Review by will-holley — CHANGES_REQUESTED** [review]
Please see comment.

**Comment by amsos** [comment]
updated

@will-holley heads up im not an "actual" developer so not 100% sure what dropping the directory means 😂 but i think you're just asking I delete the folder for now?

updated the pr as such.  lmk if this was wrong

**Review by will-holley — APPROVED** [review]

**Pull request merged**
